### ISSUE TITLE
Site search doesn't work

### ISSUE THREAD

**Issue by nitr0man** [NCCloud/pystackpath#39]
Site search/pagination doesn't work. It seems like it's a typo error:
```
class CdnSites(BaseSite):
    def index(self, first="", after="", filter="", sort_by=""):
        return super(CdnSites, self).index(first="", after="", filter="", sort_by="")
```
all args here are ignored.

**Comment by sandromodarelli** [comment]
Hello @nitr0man . Thank you for the report. Can you also provide a PR to fix it?

**Comment by nitr0man** [comment]
Done, it's quite simple.
