### ISSUE TITLE
Unable to open the object

### ISSUE THREAD

**Issue by CrakMedia** [NCCloud/pystackpath#42]
Hi,

trying to do simple get stacks and all I get is an object.
I'm trying to open it but... never works.

sp = Stackpath(
    os.getenv("STACKPATH_CLIENTID"),
    os.getenv("STACKPATH_APISECRET")
)

stacks = sp.stacks().index()
print(stacks)

{'results': [<pystackpath.stacks.Stacks object at 0x110252790>], 'pageinfo': <pystackpath.util.PageInfo object at 0x110af5e90>}

Can you please let me know?

Thanks
Math

**Comment by prometherion** [comment]
Actually, all the `index` functions return an object made of two keys:

* `results`
* `pageinfo`

To access your _stack_, you have to access the array on results, YMMV:

```python
sp = Stackpath(
os.getenv("STACKPATH_CLIENTID"),
os.getenv("STACKPATH_APISECRET")
)

stacks = sp.stacks().index()
results = stacks['results']
if results is not None:
  print(results[0].dumpdict())
````

This library didn't implement the `__repr__` method, so there's no nice string representation.
To view content of it, just _dump_ the dictionary and access as an object.

If everything is clear, please close the issue :)

**Comment by CrakMedia** [comment]
This is perfect!! 
Thank you so much for your time! 
Have a great year! :D 

Cheers! 
Math
